### PR TITLE
Use standard_intro_elements instead of the deprecated add_intro_editor

### PR DESCRIPTION
**Pull request by xow**
Currently there's a developer warning if you use add_intro_editor

### CODE REVIEW

**Comment by mudrd8mz** [comment]
Thanks John. I am just thinking, would something like https://github.com/mudrd8mz/moodle-mod_stampcoll/blob/master/mod_form.php#L52 be better to maintain backwards compatibility of this template?

**Comment by xow** [comment]
I guess so, if we want to promote such checks being used by plugin developers to maintain cross compatibility between moodle version.

**Comment by mudrd8mz** [comment]
> if we want to promote such checks

Well, they are quite common in real plugins out there. The alternative is to maintain our templates on individual branches.

**Comment by xow** [comment]
Updated let me know what you think

**Comment by mudrd8mz** [comment]
I think you simply rock. Thanks John.

**Pull request merged**
