### PR TITLE
Capabilities, readme, copyright

### PR DESCRIPTION
**Pull request by marinaglancy**
1. Capabilities definition in access.php was not fully correct and strings for the capabilities were missing
2. Readme recommends to use XMLDB editor before module installation - it is impossible
3. Corrected copyright to be the same in all files and use 2016 for the year

### CODE REVIEW

**Comment by luisdev** [comment]
I think that the "Go to Settings > Site Administration > Development > XMLDB editor  and modify the module's tables" instruction still needs a bit more explanation. What does "modify the module's tables" mean? How must you modify them? What should you do?

**Comment by mudrd8mz** [comment]
> What should you do?

Well I believe that the module author knows what DB tables the module will need. Teaching about the DB design is beyond the scope of this template. Maybe that instead of "modify the module's tables" there could be something like "define the module's DB tables as needed" or something like that?

**Comment by mudrd8mz** [comment]
> Readme recommends to use XMLDB editor before module installation - it is impossible

@marinaglancy I remember it was possible to access the XMLDB editor as the plugin's installation was not triggered as long as its version was set to zero. We might have lost this feature now (might be as well seen as a bug) but I believe it should still be possible to access the XMLDB directly by URL `/admin/tool/xmldb/`.

**Comment by marinaglancy** [comment]
@mudrd8mz it is possible to access XMLDB editor but you will not see the new module there until it is installed. Yes I assume this has changed in the later versions but I don't really think it's a bug

**Comment by luisdev** [comment]
Yes David, module authors should know what table structure their plugins require, but "modify the module's tables" doesn't really say much. It should be a bit more clear that the XMLDB editor is where you "design" the tables and where the install.xml file gets created. So maybe something like this would be an improvement:

```
- Go to Settings > Site Administration > Development > XMLDB editor 
- and modify the module's tables.  

+ Go to Settings > Site Administration > Development > XMLDB editor
+ and define the database tables that your module requires. This will generate the /db/install.xml file 
+ that you will package with your module.
```

**Comment by marinaglancy** [comment]
Luis, the initial db/install.xml with the required table is already included in this template. It is inaccurate to say that this file will be generated. Plugin developers may wish to add more fields to this table and/or add more tables. I agree with David that more information on how and why to use XMLDB editor will be excessive in this short readme.

**Pull request merged**
